-- CreateEnum
CREATE TYPE "PropertyLocation" AS ENUM ('JATRABARI', 'JURAINE', 'MOTIJHEEL', 'TIKATULI', 'DOYAGANJ', 'GULISTAN', 'MUGDA', 'MANDA', 'KAMRAPUR', 'FAKIRAPUL', 'GOLAPBAG', 'GOPIBAGBASABO', 'KHILGAON', 'RAMPURA', 'BANASRI', 'HATIRJHEEL', 'DHANMONDI', 'JIGATOLA', 'FARMGATE');

-- AlterEnum
ALTER TYPE "RentStatus" ADD VALUE 'PENDING';

-- AlterTable
ALTER TABLE "properties" ADD COLUMN     "areaInSqFt" INTEGER NOT NULL DEFAULT 1000,
ADD COLUMN     "location" "PropertyLocation" NOT NULL DEFAULT 'JATRABARI';
